default: &default
  adapter: postgresql_proxy
  encoding: unicode
  pool: 5
  username: postgres
  password: secret
  database: appdb

development:
  primary:
    <<: *default
    host: pg-primary
  primary_replica:
    <<: *default
    adapter: postgresql
    host: pg-replicas
    replica: true
